project:
  type: book

sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://openscapes.org
        text: "Openscapes.org"
      - icon: github
        href: https://github.com/openscapes/quarto-website-tutorial
        text: "Quarto website tutorial"
      - icon: twitter
        href: https://twitter.com/openscapes
        text: "Openscapes Twitter"  


book:
  title: <span style="color:#003300;">Manejo Integrado de la Arbovirosis en México</span>
  subtitle: <span style="color:#003300;">Con Énfasis en Áreas Urbanas Endémicas de Dengue y en Aedes Aegypti</span>
  author: "Felipe Dzul-Manzanilla | Fabián Correa-Morales"
  date: "2023-08-01"
  site-url: https://github.com/fdzul/
  repo-url: https://github.com/fdzul/
  chapters:
    - index.qmd
    - intro.qmd
    - objetivo.qmd
    - part: part1.qmd
      chapters:
        - mia_mx.qmd
    - part: part2.qmd
      chapters:
        - hotspots_transmision_persistente.qmd
        - hotspots_vector.qmd
        - definicion_escenarios_operativos.qmd
    - part: part3.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    link-external-icon: true
    title-block-banner: false
    date-modified: "2023-08-01"
    last-modified: true
    embed-resources: true
    theme: cosmo
    number-depth: 3
    code-fold: false
    code-summary: "Code"
    code-tools: true
    code-link: true
    knitr:
      opts_chunk:
        out.width: 100%
        R.options:
          width: 68