# Manejo Integrado de Aedes


EL MIV incluye un portafolio de intervenciones combinadas y sincronizadas en tiempo y espacio basado en el conocimiento de la biología de los vectores, ciclos de transmisión, inmunidad de las poblaciones humanas y condiciones sociales y ecológicas. El fin ultimo de manejo integrada de vectores es reducir o interrumpir la transmisión por medio de la prevención, reducción y/ó eliminación de las condiciones que favorecen el desarollo y las abundancias de los vectores. 

En el documento títulado la **Respuesta Global para el Control del Vector** de la Organización Mundial de la Salud (OMS, 2017) se proporciona una guía para fortalecer el control integrado de vectores a través del fortalecimiento de la capacidad, una mejor vigilancia, una mejor coordinación y una acción integrada entre sectores y enfermedades. 

Basados en estas directrices, organizaciones y investigadores han generado documentos ilustrativos que intentan operacionalizar el Manejo Integrado de Aedes (MIA) describiendo escenarios epidemiológicos y operativos a nivel de localidades (Roiz et al 2019) y en el interior de las areas urbanas endemicas de dengue (PAHO et al 2019; PAHO 2020; WHO,2023). 

El programa Nacional de Prevención y Control de las Enfermedades Tranmitidas por Vectores (ETVs) e Intoxicación por  Veneno de Artrópodos (IVA) de la Secretaría de Salud, basados en el Manejo Integrado de Vectores (MIV) de la Organización Mundial de la Salud (WHO, 2017) definen e implementan el Manejo Integrado de las Arbovirosis (MIA) en México.



```{r ana, echo=FALSE, out.width='100%', fig.align='center'}
DiagrammeR::grViz("digraph {
                  # graph definitions
  graph [layout = dot, rankdir = TB]
  
  # node definitions
  node [shape = rectangle, 
  style = filled, 
  color = grey, 
  nodesep = .5,
  fixedsize = true, 
  width = 2.5] 
  
  # edge definition
  edge [color = grey, arrowhead = normal, arrowtail = dot]
  
  ##### epidemiological data
  
  epi [label = 'Vigilancia Epidemiológica',  fillcolor =  '#DB4437', color = 'white', fontcolor = 'white']
  data_historic [label = 'Datos Históricos',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_datos_actuales [label = 'Datos Actuales',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_acumulados [label = 'Datos Acumulados',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  data_trans_activa [label = 'Transmisión Activa',  fillcolor =  'gray', color = 'white', fontcolor = 'white']
  
  
  ##### Spatial Data
  
  areal [label = 'Areal Data',  fillcolor =  '#0F9D58', color = 'white', fontcolor = 'white']
  pp_data [label = 'Point Pattern Data',  fillcolor =  ' #0F9D58', color = 'white', fontcolor = 'white']
  
  
 
 # Análisis 
 hotspots [label = 'Hotspots Analysis',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 cadenas [label = 'Cadenas de Transmisión',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 cluster_ana [label = 'Cluster Analysis',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 lgcp [label = 'Spatial LGCP',  fillcolor =  'orange', color = 'white', fontcolor = 'black']
 
 
 # software
 
 geoda [label = 'Geoda',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 cluster_s [label = 'ClusterSeer',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 satscan [label = 'SatScan',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
 
 r_rstudio [label = 'R & RStudio',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']

  denhotspot [label = 'denhotspots Package',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white'] 
 
 ##### define the relation
 
 epi -> {data_historic  data_datos_actuales}
 data_historic -> areal -> hotspots -> geoda
 data_datos_actuales -> {data_acumulados, data_trans_activa} -> pp_data -> {cadenas cluster_ana lgcp}
 cadenas -> cluster_s
 cluster_ana -> satscan
 
 {geoda cluster_s satscan lgcp} -> r_rstudio -> denhotspot
 
}")

```



